### ISSUE TITLE
Dupe recipes

### ISSUE THREAD

**Issue by timsutton** [autopkg/cgerke-recipes#2]
Hi Chris,

A question came up today on autopkg-discuss of which Java munki recipes to use, as someone had done a search and also saw yours. I know you have added some additional recipes for .install and .sccm, but I was curious why you also duplicate (or seemed to) the .download, .pkg and .munki recipes from the autopkg/recipes repo?

Generally we try to keep it so that if someone has written a variant of an existing recipe they add descriptive info as to why their recipe exists and how it differs from a recipe for the same application/update. But looking at yours it's not immediately clear to me if yours are any different?

**Comment by timsutton** [comment]
Some more background: https://groups.google.com/d/msg/autopkg-discuss/_yjaoIh31aw/XEbdwa013GsJ

**Comment by cgerke** [comment]
Just internal policy that I write the recipe rather than use someone else so if we miss any changes someone is doing it wont affect any systems internally, I am removing my dupes and keeping them inhouse.
