### ISSUE TITLE
Citrix Receiver is being re-branded as Citrix Workspace

### ISSUE THREAD

**Issue by smashism** [autopkg/cgerke-recipes#20]
Just kind of an FYI, I'm unsure what the impact will be on how the pkg recipe and the other recipes that rely on it will be impacted (I have opened separate issues on the download and jss recipes). Citrix is rebranding Receiver as Workspace, and will stop updating Receiver. Unsure on timeline. Workspace is already available.

https://www.citrix.com/products/citrix-workspace/

**Comment by cgerke** [comment]
Hey sorry, haven't visited these in a while since I've been off mac support. Got a PR for it or shall I build one?

**Comment by cgerke** [comment]
Two different apps. Leaving receiver...will build a workspace.
