### ISSUE TITLE
Wireshark 3.0

### ISSUE THREAD

**Issue by chelming** [autopkg/cgerke-recipes#21]
Looks like the Wireshark.download.recipe is hard-coded to look for version 2.x. Version 3 was released within the past two weeks.

**Comment by cgerke** [comment]
Got a pr for this? Probably just this guy needing a change to 3

<string>(Wireshark 2.* 64.dmg)</string>

**Comment by cgerke** [comment]
patched f30c7ea

**Comment by chelming** [comment]
Is this working for you? I'm getting:
```
PkgPayloadUnpacker: Error: extraction of /Volumes/Data/AutoPkg/Cache/local.munki.Wireshark/unpack/wireshark.pkg/Payload with ditto failed: ditto: /Volumes/Data/AutoPkg/Cache/local.munki.Wireshark/payload//Wireshark.app/Contents/Frameworks/QtPrintSupport.framework/Resources: Is a directory
```

**Comment by cgerke** [comment]
Working fine for me. What's up with your path _**payload//Wireshark.app**_ ? doesn't look right there.

**Comment by chelming** [comment]
Looks like it had to do with my Cache. I emptied it and it worked.
