### ISSUE TITLE
Wireshark has garbage receipts

### ISSUE THREAD

**Issue by chelming** [autopkg/cgerke-recipes#22]
This will cause subsequent versions to not be imported if Wireshark doesn't fix it themselves.
```	<key>receipts</key>
	<array>
		<dict>
			<key>installed_size</key>
			<integer>296264</integer>
			<key>packageid</key>
			<string>org.wireshark.Wireshark.pkg</string>
			<key>version</key>
			<string>0.0.0.0</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>8</integer>
			<key>packageid</key>
			<string>org.wireshark.ChmodBPF.pkg</string>
			<key>version</key>
			<string>1.0</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>4</integer>
			<key>packageid</key>
			<string>org.wireshark.cli.pkg</string>
			<key>version</key>
			<string>1.0</string>
		</dict>
	</array>
```

**Comment by cgerke** [comment]
Thoughts?

**Comment by chelming** [comment]
Borrow the stuff from here I guess? https://github.com/autopkg/jleggat-recipes/blob/master/Wireshark/Wireshark.munki.recipe

**Comment by cgerke** [comment]
You'll have to do a PR for this, I have no way to test it anymore since I don't have any running Munki installations.

**Comment by chelming** [comment]
If that's the case you should just delete the recipes and add a readme.md telling people to move to the jleggat-recipes.

**Comment by cgerke** [comment]
I considered that, wasn't sure how many people (if any) were using my recipes and would start getting errors though.

**Comment by chelming** [comment]
They'd come to your repo to file an issue and see the readme. It's been done before on other repos.

**Comment by cgerke** [comment]
Have you tested jleggat-recipes? There is an open issue with the Wireshark.download.recipe that the Wireshark.munki.recipe relies on.

**Comment by chelming** [comment]
Yeah, I used it yesterday to grab 3.0.0 and it properly created an installs array for munki.

**Comment by apizz** [comment]
Looks like this can be closed as well
