### ISSUE TITLE
ChromeRemoteDesktop input_plist_path needs to be .app not .bundle

### ISSUE THREAD

**Issue by sau70networkadmin** [autopkg/cgerke-recipes#25]
Hi,

I was getting 

  Error in local.munki.ChromeRemoteDesktop: Processor: Versioner: Error: File '/Users/admin/Library/AutoPkg/Cache/local.munki.ChromeRemoteDesktop/payload/Library/PrivilegedHelperTools/ChromeRemoteDesktopHost.bundle/Contents/Info.plist' does not exist or could not be read.

when I tried to run apizz's derived Munki recipe. Once I changed

<string>%RECIPE_CACHE_DIR%/payload/Library/PrivilegedHelperTools/ChromeRemoteDesktopHost.bundle/Contents/Info.plist</string>

to                 

<string>%RECIPE_CACHE_DIR%/payload/Library/PrivilegedHelperTools/ChromeRemoteDesktopHost.app/Contents/Info.plist</string>

it worked for me. Thanks!

-- MB

**Comment by b3to** [comment]
where do you change that ? @sau70networkadmin

**Comment by sau70networkadmin** [comment]
In the recipe override file:

 <key>input_plist_path</key>
<string>%RECIPE_CACHE_DIR%/unpacked/Library/PrivilegedHelperTools/ChromeRemoteDesktopHost.**app**/Contents/Info.plist</string>
 
Remember to clear the autopkg cache before you rerun it.

**Comment by homebysix** [comment]
If this is still an issue, it should be changed in the repository hosting the Munki recipe, here: https://github.com/autopkg/zentral-recipes/blob/422630dc3383e22b50ba9c23ec9f717533652fa2/Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe#L112
