### ISSUE TITLE
Wireshark No match found on URL: https://www.wireshark.org/download/osx/

### ISSUE THREAD

**Issue by master-vodawagner** [autopkg/cgerke-recipes#30]
Getting the following errors when your Wireshark recipe is executed

No match found on URL: https://www.wireshark.org/download/osx/

URL appears to be valid so must be the search condition in the download recipe

**Comment by rustymyers** [comment]
@cgerke Looks like pull #29 and #31 are both to fix the Wireshark updates. Would you please pull one in?
Thanks
Rusty

**Comment by rustymyers** [comment]
Resolved, thank you!!

**Comment by cgerke** [comment]
Apologies for the delay, unfortunately I don’t manage macs in an enterprise anymore so it’s purely hobby stuff at the moment.
