### ISSUE TITLE
Recipe transfer and eventual repo archive

### ISSUE THREAD

**Issue by homebysix** [autopkg/cgerke-recipes#37]
Hello @cgerke!

Given [this comment](https://github.com/autopkg/cgerke-recipes/pull/23#issuecomment-559901816) I'm inclined to take over a subset of recipes from this repo. I would focus on application recipes that are referenced elsewhere and/or still functioning correctly.

Here's the process I envision:

1. I create new copies of recipes that I feel I can be responsible for in my [homebysix-recipes](https://github.com/autopkg/homebysix-recipes) repo.
2. I submit PRs to any recipes in the AutoPkg org to change their `ParentRecipe` from the old recipe to my new recipe.
3. I add `DeprecationWarning` to the corresponding recipes in this repo, with a message pointing people to the new recipe.
4. After some period of time, we archive and close the cgerke-recipes repository permanently.

This would mean that **SCCM** and **config pkg** recipes would be facing permanent removal. I don't have a sense of how widely used these recipes are, but my guess is you might have been the sole consumer of most of them. Does that sound right?

Any thoughts on the above plan?

**Comment by cgerke** [comment]
Yeah mate happy for you to proceed. It was fun while it lasted.

**Comment by homebysix** [comment]
Repository has been archived. Thank you for contributing and maintaining as long as you did!
