### ISSUE TITLE
MySQLWorkBench.munki Traceback

### ISSUE THREAD

**Issue by gmarnin** [autopkg/cgerke-recipes#7]
Heads up, I get the following error when I run MySQLWorkBench.munki

The following recipes failed:
    MySQLWorkBench.munki
        Error in local.munki.MySQLWorkBench: Processor: MunkiImporter: Error: creating pkginfo for /Users/autopkg/Library/AutoPkg/Cache/local.munki.MySQLWorkBench/MySQLWorkBench-6.0.pkg failed: Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 1157, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 1135, in main
    item = catinfo['name']
KeyError: 'name'

**Comment by foigus** [comment]
Marnin,

  Does this accepted PR fix your issue?

https://github.com/autopkg/cgerke-recipes/pull/6

**Comment by cgerke** [comment]
Looks good to me.

**Comment by gmarnin** [comment]
Looks fixed to me. Thanks all!
