### ISSUE TITLE
MySQLWorkBench.pkg.recipe  missing version

### ISSUE THREAD

**Issue by aa-it-autopkg** [autopkg/cgerke-recipes#8]
Jssimportor can't detect version from pkg recipe

**Comment by foigus** [comment]
aa-it-autopkg,

  Does this accepted PR fix your issue?

https://github.com/autopkg/cgerke-recipes/pull/6

**Comment by cgerke** [comment]
Looks good to me.

**Comment by cgerke** [comment]
#6 closes
